from __future__ import annotations

from pathlib import Path

from memory_migrate_plugin.utils import ensure_dir, write_text


ADAPTER_DOC_DIR = Path("docs") / "adapters"
ADAPTER_SRC_DIR = Path("src") / "memory_migrate_plugin" / "adapters"
TESTS_DIR = Path("tests")


def _to_pascal_case(value: str) -> str:
    parts = [part for part in value.replace("_", "-").split("-") if part]
    return "".join(part[:1].upper() + part[1:] for part in parts) or "Custom"


def derive_adapter_names(adapter_name: str, class_name: str | None = None) -> dict[str, str]:
    normalized_name = adapter_name.strip().lower()
    if not normalized_name:
        raise ValueError("adapter_name must be a non-empty string")
    module_name = normalized_name.replace("-", "_")
    resolved_class_name = class_name.strip() if class_name else f"{_to_pascal_case(normalized_name)}Adapter"
    return {
        "adapter_name": normalized_name,
        "module_name": module_name,
        "class_name": resolved_class_name,
        "fixture_dir_name": normalized_name,
    }


def build_adapter_module(context: dict[str, str]) -> str:
    template = '''from __future__ import annotations

from pathlib import Path

from memory_migrate_plugin.adapters.base import BaseAdapter
from memory_migrate_plugin.models import CanonicalMemoryPackage, MemoryEntry
from memory_migrate_plugin.utils import ensure_dir, read_text, write_text


class {class_name}(BaseAdapter):
    name = "{adapter_name}"
    description = "TODO: describe the {adapter_name} memory format."

    def probe(self, path: Path) -> bool:
        return path.exists()

    def detect_confidence(self, path: Path) -> int:
        return 20 if self.probe(path) else 0

    def read(self, path: Path) -> CanonicalMemoryPackage:
        package = CanonicalMemoryPackage(package_id=path.stem or self.name, source_formats=[self.name])
        if path.is_file():
            package.add_entry(
                MemoryEntry(
                    id=f"{{self.name}}-root",
                    kind="note",
                    title=path.stem or self.name,
                    content=read_text(path),
                    source_format=self.name,
                    metadata={{"source_path": str(path)}},
                )
            )
        return package

    def write(self, package: CanonicalMemoryPackage, path: Path) -> None:
        ensure_dir(path)
        for entry in package.entries:
            target = path / f"{{entry.id}}.md"
            write_text(target, f"# {{entry.title}}\n\n{{entry.content}}\n")
'''
    return template.format(**context)


def build_test_module(context: dict[str, str]) -> str:
    template = '''from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from memory_migrate_plugin.adapters.{module_name} import {class_name}
from memory_migrate_plugin.models import CanonicalMemoryPackage, MemoryEntry


class {class_name}Tests(unittest.TestCase):
    def test_read_returns_canonical_package(self) -> None:
        adapter = {class_name}()
        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "sample.txt"
            source.write_text("Example memory", encoding="utf-8")
            package = adapter.read(source)
            self.assertEqual(package.source_formats, [adapter.name])
            self.assertEqual(len(package.entries), 1)

    def test_write_creates_markdown_files(self) -> None:
        adapter = {class_name}()
        package = CanonicalMemoryPackage(
            package_id="demo",
            source_formats=[adapter.name],
            entries=[
                MemoryEntry(
                    id="entry-1",
                    kind="note",
                    title="Entry 1",
                    content="Example content",
                    source_format=adapter.name,
                )
            ],
        )
        with tempfile.TemporaryDirectory() as tmpdir:
            output = Path(tmpdir) / "out"
            adapter.write(package, output)
            self.assertTrue((output / "entry-1.md").exists())


if __name__ == "__main__":
    unittest.main()
'''
    return template.format(**context)


def build_adapter_doc(context: dict[str, str]) -> str:
    template = '''# {class_name}

This scaffold was generated by `memory-migrate init-adapter`.

## Adapter contract

- module: `src/memory_migrate_plugin/adapters/{module_name}.py`
- class: `{class_name}`
- registry name: `{adapter_name}`
- starter test: `tests/test_{module_name}_adapter.py`

## Next steps

1. Replace the placeholder `probe()` logic with real format detection.
2. Implement `read()` so it maps source files into canonical entries.
3. Implement `write()` so it exports canonical entries back into the target layout.
4. Register the adapter in `src/memory_migrate_plugin/adapters/__init__.py`.
5. Register the adapter in `src/memory_migrate_plugin/registry.py`.
6. Add fixture samples under `fixtures/{fixture_dir_name}`.
7. Add roundtrip coverage and detection tests.
'''
    return template.format(**context)


def init_adapter(adapter_name: str, output_root: Path, class_name: str | None = None) -> dict[str, str]:
    context = derive_adapter_names(adapter_name, class_name)
    adapter_path = output_root / ADAPTER_SRC_DIR / f'{context["module_name"]}.py'
    test_path = output_root / TESTS_DIR / f'test_{context["module_name"]}_adapter.py'
    doc_path = output_root / ADAPTER_DOC_DIR / f'{context["module_name"]}.md'

    targets = {
        "adapter": adapter_path,
        "test": test_path,
        "doc": doc_path,
    }
    collisions = [label for label, path in targets.items() if path.exists()]
    if collisions:
        joined = ", ".join(collisions)
        raise FileExistsError(f"Refusing to overwrite existing scaffold targets: {joined}")

    ensure_dir(adapter_path.parent)
    ensure_dir(test_path.parent)
    ensure_dir(doc_path.parent)

    write_text(adapter_path, build_adapter_module(context))
    write_text(test_path, build_test_module(context))
    write_text(doc_path, build_adapter_doc(context))

    return {
        "adapter_name": context["adapter_name"],
        "class_name": context["class_name"],
        "module_name": context["module_name"],
        "adapter_path": str(adapter_path),
        "test_path": str(test_path),
        "doc_path": str(doc_path),
    }
